#!/bin/bash
# vim: syntax=sh

# This will create surfix alias to open a file with the associated application.
# Input:
# - Application name
# - List of file extention
make_alias_open(){
    # App name should be the fisrt input,
    app="$1"

    shift # Ignore the first param, which is the app name.

    # Loop through the rest of argument list to make surfix alias
    for ext; do
      alias -s $ext=$app
    done
    unset ext
}

make_alias_open vim\
  vim md c cpp cs css xml rc tex py java scala

make_alias_open vlc\
  mp4 flv avi mkv

make_alias_open eog\
  jpg png jpeg bmp

# I often want to detach zathura, so I reuse my custom function for zathura
alias -s pdf=za

# I still change my configuration a lot, so I wanna shorten the typing.
alias so="source"
alias r="ranger"
alias v="vim -R"
alias vw="vim +VimwikiIndex"
alias vd="vim +VimwikiDiaryIndex"
alias vt="vim +VimwikiMakeDiaryNote +Goyo"
alias sv="sudo vim"

# This help to send Ctrl-S to vim. I map <C-S> to save current editing file.
alias vim="stty stop '' -ixoff; nvim"

# Get current day, useful for some lazy commands.
alias today="date +%Y-%m-%d"

# Alias for the cmus player
alias cr="cmus-remote"
alias crst="cmus-remote -Q" # Status
alias crn="cmus-remote --next"
alias crr="cmus-remote --prev"
alias crp="cmus-remote --play"
alias cru="cmus-remote --pause"
alias crs="cmus-remote --stop"
alias crvu="cmus-remote -v +10%"
alias crvd="cmus-remote -v -10%"

# Use ag with the global agignore file
alias ag='ag --path-to-agignore ~/.agignore'
