#!/bin/bash
# vim: syntax=sh
# Custom key binding
# pressing ctlr-k to pipe output to less
bindkey -s "^k" "| less^m"
bindkey -s "^]" "^e | clipcopy^m"
bindkey "^ " "autosuggest-accept"
bindkey -e

# enable edit-command-line
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

