#!/bin/bash
# vim: syntax=sh

export EDITOR="nvim"
export LANG=en_US.UTF-8
export PATH="$PATH:$HOME/.local/bin"
export FZF_DEFAULT_OPTS='--height 80% --reverse --preview "highlight -O ansi -l {} 2> /dev/null || ls -lah {}"'
