#!/bin/bash
# vim: syntax=sh

export LANG=en_US.UTF-8
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.npm-global/bin"
export FZF_DEFAULT_OPTS='--height 60% --reverse --preview "head -50 {}"'
export TERM=xterm-256color-italic
