#!/bin/bash
# vim: syntax=sh foldenable foldmethod=marker

# Some custom functions, and also the aliases for make them shorten when using.
# Because the functions is self-defined, their aliases should be kept here, not
# in the ~/.aliases file.


# Open the ebook from command line using zathura, this also make za an alias to
# zathura.
# Usage:
#   za [file_name]
# If file_name is not provided, simply open zathura.
za(){
if [ $# -eq 0 ]; then
    (zathura &)
else
    (zathura "$1" &)
fi
}


# Add, commit and push in single call. For lazy people.
# Shouldn't use this on serious project. It's would pollute your git history!
function lazygit() {
if [ $# -eq 0 ]; then # Check for commit message
  echo "Need a commit message"
  return 1
fi
git add .
git commit -a -m "$*"
git push
}

alias lg="lazygit" # And even more lazy


function quit_session {
if ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
  # Not in a tmux session, just do normal exit.
  exit
else
  tmux detach
fi
}

alias exit=quit_session
# This is a habit when using Vim, and I want to make this habit work
alias :q=quit_session


# Inverse recursive search for a find name
# Usage:
#    findup <file_name>
findup(){
    file_name=$1
    current_dir=$(pwd)
    local  result=1

    while [[ "$(pwd)" != "/" ]]; do
        if [ -f "${file_name}" ]; then
            echo "$(pwd)" "/" "${file_name}"
            result=0
            break
        fi
        cd ..
    done

    if [ ${result} -eq 1 ]; then
        echo "Cannot found ${file_name}"
    fi

    cd "${current_dir}"
    return ${result}
}

# Commit and push the latest change in my personal note project (super lazy, huh ☺)
lgn(){
  if [ -z "$NOTE" ]; then
    echo NOTE folder is not configured, discard.
    return
  fi
  if [ "$(pwd)" != "$NOTE" ];then
    echo Not in NOTE folder, discard.
    return
  fi

  lg Add note for "$(today)"
}
