" Avoid changing inode of the current file on saving
" https://unix.stackexchange.com/questions/36467/why-inode-value-changes-when-we-edit-in-vi-editor
set backupcopy=yes
set nocompatible
set mouse=ar
set nu

syntax on
filetype plugin indent on

" avoid UI lagging when new sign appear and show more than 1 sign
set signcolumn=number

set undofile

source ~/.vim/plugins.vim

let mapleader="\<SPACE>"
let maplocalleader="\<SPACE>"

" Quickly open vimrc and apply change
nnoremap <Leader>ve :tabedit $MYVIMRC<CR>
nnoremap <Leader>vp :tabedit ~/.vim/plugins.vim<CR>
nnoremap <Leader>vl :tabedit ~/.vimrc_local<CR>
nnoremap <Leader>vL :tabedit ~/.local.plugins.vim<CR>
nnoremap <Leader>va :so $MYVIMRC<CR>

" remap key to escape terminal mode
tnoremap <Leader><c-c> <c-\><c-n>

" Search in the command line
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" " (useful for handling the permission-denied error)
command! SW w !sudo tee % > /dev/null

" Reduce time waiting for mapped sequence
set timeoutlen=300

let vimwiki_html_path = $HOME.'/vimwiki_html/'
let wiki = {}
let wiki.path = $NOTE
let wiki.syntax = 'default'
let wiki.ext = '.wiki'
let wiki.path_html = vimwiki_html_path
let wiki.template_path = vimwiki_html_path.'assets/'
let wiki.template_default = 'default'
let wiki.template_ext = ".html"
let wiki.nested_syntaxes ={
      \'python': 'python',
      \'ruby': 'ruby',
      \'py':     'python',
      \'sql':     'pgsql',
      \'c++':    'cpp',
      \'c':      'c',
      \'scala':  'scala',
      \'java':   'java',
      \'js':   'javascript',
      \'gql':   'graphql',
      \'go':   'go',
      \'graphql':   'graphql'
      \}

let g:vimwiki_list = [wiki]
let g:vimwiki_hl_headers=1
let g:vimwiki_hl_cb_checked=1
let g:vimwiki_conceallevel=0
let g:vimwiki_conceal_onechar_markers=0
let g:vimwiki_global_ext=0

" Triger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
" Notification after file change
" https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
autocmd FileChangedShellPost *
      \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None


command! BufOnly silent! execute "%bd|e#|bd#"
