#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

MIME=$(file -Lb --mime-type "$file")

case "$MIME" in
  *image/*)
  kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
  ;;
  # .pdf
  *application/pdf*)
  pdftotext "$1" -
  ;;
  # .7z
  *application/x-7z-compressed*)
  7z l "$1"
  ;;
  # .tar .tar.Z
  *application/x-tar*)
  tar -tvf "$1"
  ;;
  # .tar.*
  *application/x-compressed-tar*|*application/x-*-compressed-tar*)
  tar -tvf "$1"
  ;;
  # .rar
  *application/vnd.rar*)
  unrar l "$1"
  ;;
  # .zip
  *application/zip*)
  unzip -l "$1"
  ;;
  *)
  pistol "$file"
  ;;
esac

