[[mgr.prepend_keymap]]
on = "T"
run = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on = ["$"]
run = 'shell zsh --block --confirm'
desc = "Open PowerShell here"

[[mgr.prepend_keymap]]
on = ["g", "n"]
run = 'cd ~/Projects/mine/ms-notes'
desc = "Go to MS Notes"

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = 'cd ~/Projects/ms/'
desc = "Go to MS repos"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = 'cd ~/temp'
desc = "Go to Temp"

[[mgr.prepend_keymap]]
on = ["g", "x"]
run = 'shell "xdg-open $@" --confirm --orphan'
desc = "Explorer here"

[[mgr.prepend_keymap]]
on = ["<C-o>"]
run = 'back'
desc = "Back in history"

[[mgr.prepend_keymap]]
on = ["<C-i>"]
run = 'forward'
desc = "Forward in history"
